name = "telegram-cpa-bot"
main = "index.js"
compatibility_date = "2025-09-11"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[vars]
BOT_TOKEN = ""
TELEGRAM_SECRET_TOKEN = ""
ADMIN_ID = ""
CALLBACK_SECRET = ""
DATABASE_URL = ""
