name = "telegram-cpa-bot"
main = "src/index.js"
compatibility_date = "2025-09-08"

# تفعيل السجلات (Logs) لمراقبة الأداء والأخطاء
[observability.logs]
enabled = true

# تعريف متغيرات البيئة (سيتم تعيين القيم الفعلية لاحقًا من لوحة Cloudflare)
[vars]
BOT_TOKEN = ""
TELEGRAM_SECRET_TOKEN = ""
ADMIN_ID = ""
CALLBACK_SECRET = ""
DATABASE_URL = ""
