name = "telegram-cpa-bot"
main = "index.js"
compatibility_date = "2025-09-10"

# لو محتاج nodejs built-ins زي (fs, path, crypto ...) لازم تفعّل
compatibility_flags = ["nodejs_compat"]

# تفعيل السجلات (Logs) لمراقبة الأداء والأخطاء
[observability.logs]
enabled = true

# تعريف متغيرات البيئة (غيّر القيم من Dashboard)
[vars]
BOT_TOKEN = ""
TELEGRAM_SECRET_TOKEN = ""
ADMIN_ID = ""
CALLBACK_SECRET = ""
DATABASE_URL = ""
