name = "telegram-cpa-bot"
main = "src/index.js"
compatibility_date = "2025-09-11"

# ✅ عشان تشتغل مكتبات Node.js (fs, crypto, stream, ...)
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[vars]
BOT_TOKEN = ""
TELEGRAM_SECRET_TOKEN = ""
ADMIN_ID = ""
CALLBACK_SECRET = ""
DATABASE_URL = ""
