name = "telegram-cpa-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

# تعريف متغيرات البيئة (سيتم تعيين القيم الفعلية لاحقًا في لوحة Cloudflare)
[vars]
BOT_TOKEN = ""
TELEGRAM_SECRET_TOKEN = ""
ADMIN_ID = ""
CALLBACK_SECRET = ""
DATABASE_URL = ""
